# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_reactor_window.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from template import bree_rc

class Ui_BreeReactorMainWindow(object):
    def setupUi(self, BreeReactorMainWindow):
        if not BreeReactorMainWindow.objectName():
            BreeReactorMainWindow.setObjectName(u"BreeReactorMainWindow")
        BreeReactorMainWindow.resize(1496, 826)
        icon = QIcon()
        icon.addFile(u":/bree/magnet32.png", QSize(), QIcon.Normal, QIcon.Off)
        BreeReactorMainWindow.setWindowIcon(icon)
        self.actionNovo_projeto = QAction(BreeReactorMainWindow)
        self.actionNovo_projeto.setObjectName(u"actionNovo_projeto")
        icon1 = QIcon()
        icon1.addFile(u":/bree/blue-document.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNovo_projeto.setIcon(icon1)
        self.actionCondutores = QAction(BreeReactorMainWindow)
        self.actionCondutores.setObjectName(u"actionCondutores")
        self.actionMateriais = QAction(BreeReactorMainWindow)
        self.actionMateriais.setObjectName(u"actionMateriais")
        self.actionProjetos = QAction(BreeReactorMainWindow)
        self.actionProjetos.setObjectName(u"actionProjetos")
        self.actionFim = QAction(BreeReactorMainWindow)
        self.actionFim.setObjectName(u"actionFim")
        icon2 = QIcon()
        icon2.addFile(u":/bree/cross.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionFim.setIcon(icon2)
        self.actionDados_do_sistema = QAction(BreeReactorMainWindow)
        self.actionDados_do_sistema.setObjectName(u"actionDados_do_sistema")
        icon3 = QIcon()
        icon3.addFile(u":/bree/glass_characteristics_electrical_insulation_yarns.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDados_do_sistema.setIcon(icon3)
        self.actionDados_construtivos = QAction(BreeReactorMainWindow)
        self.actionDados_construtivos.setObjectName(u"actionDados_construtivos")
        icon4 = QIcon()
        icon4.addFile(u":/bree/ruler.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDados_construtivos.setIcon(icon4)
        self.actionCarregar_projeto = QAction(BreeReactorMainWindow)
        self.actionCarregar_projeto.setObjectName(u"actionCarregar_projeto")
        icon5 = QIcon()
        icon5.addFile(u":/bree/document-sticky-note.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCarregar_projeto.setIcon(icon5)
        self.actionSalvar_projeto = QAction(BreeReactorMainWindow)
        self.actionSalvar_projeto.setObjectName(u"actionSalvar_projeto")
        icon6 = QIcon()
        icon6.addFile(u":/bree/folder-open-document.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSalvar_projeto.setIcon(icon6)
        self.actionCorrentes_harm_nicas = QAction(BreeReactorMainWindow)
        self.actionCorrentes_harm_nicas.setObjectName(u"actionCorrentes_harm_nicas")
        icon7 = QIcon()
        icon7.addFile(u":/bree/table.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCorrentes_harm_nicas.setIcon(icon7)
        self.actionSe_o_de_taps = QAction(BreeReactorMainWindow)
        self.actionSe_o_de_taps.setObjectName(u"actionSe_o_de_taps")
        icon8 = QIcon()
        icon8.addFile(u":/bree/sair-alt.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSe_o_de_taps.setIcon(icon8)
        self.actionAn_is_de_perdas = QAction(BreeReactorMainWindow)
        self.actionAn_is_de_perdas.setObjectName(u"actionAn_is_de_perdas")
        icon9 = QIcon()
        icon9.addFile(u":/bree/ring.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAn_is_de_perdas.setIcon(icon9)
        self.actionIsoladores_Hardware = QAction(BreeReactorMainWindow)
        self.actionIsoladores_Hardware.setObjectName(u"actionIsoladores_Hardware")
        icon10 = QIcon()
        icon10.addFile(u":/bree/Tr202 vf.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionIsoladores_Hardware.setIcon(icon10)
        self.actionFor_as_de_curto_e_vento = QAction(BreeReactorMainWindow)
        self.actionFor_as_de_curto_e_vento.setObjectName(u"actionFor_as_de_curto_e_vento")
        icon11 = QIcon()
        icon11.addFile(u":/bree/monof\u00e1sico.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionFor_as_de_curto_e_vento.setIcon(icon11)
        self.actionS_smico = QAction(BreeReactorMainWindow)
        self.actionS_smico.setObjectName(u"actionS_smico")
        icon12 = QIcon()
        icon12.addFile(u":/bree/tremor-de-terra.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionS_smico.setIcon(icon12)
        self.actionCampo_magn_tico = QAction(BreeReactorMainWindow)
        self.actionCampo_magn_tico.setObjectName(u"actionCampo_magn_tico")
        self.actionCampo_magn_tico.setIcon(icon)
        self.actionIndut_ncia_3_x_Fases = QAction(BreeReactorMainWindow)
        self.actionIndut_ncia_3_x_Fases.setObjectName(u"actionIndut_ncia_3_x_Fases")
        icon13 = QIcon()
        icon13.addFile(u":/bree/trif\u00e1sico.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionIndut_ncia_3_x_Fases.setIcon(icon13)
        self.actionMateriais_e_custos = QAction(BreeReactorMainWindow)
        self.actionMateriais_e_custos.setObjectName(u"actionMateriais_e_custos")
        icon14 = QIcon()
        icon14.addFile(u":/bree/counter.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMateriais_e_custos.setIcon(icon14)
        self.actionCustos = QAction(BreeReactorMainWindow)
        self.actionCustos.setObjectName(u"actionCustos")
        self.actionEspessuras_das_fibras = QAction(BreeReactorMainWindow)
        self.actionEspessuras_das_fibras.setObjectName(u"actionEspessuras_das_fibras")
        icon15 = QIcon()
        icon15.addFile(u":/bree/glass_characteristics_higher_resistance_than_steel_yarns.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionEspessuras_das_fibras.setIcon(icon15)
        self.actionCruzetas = QAction(BreeReactorMainWindow)
        self.actionCruzetas.setObjectName(u"actionCruzetas")
        icon16 = QIcon()
        icon16.addFile(u":/bree/configuracoes.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCruzetas.setIcon(icon16)
        self.actionIndut_ncia_m_dulos_iguais_em_s_rie_empilhados = QAction(BreeReactorMainWindow)
        self.actionIndut_ncia_m_dulos_iguais_em_s_rie_empilhados.setObjectName(u"actionIndut_ncia_m_dulos_iguais_em_s_rie_empilhados")
        icon17 = QIcon()
        icon17.addFile(u":/bree/calculadora.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionIndut_ncia_m_dulos_iguais_em_s_rie_empilhados.setIcon(icon17)
        self.centralwidget = QWidget(BreeReactorMainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.labelImage = QLabel(self.centralwidget)
        self.labelImage.setObjectName(u"labelImage")
        self.labelImage.setScaledContents(True)

        self.horizontalLayout.addWidget(self.labelImage)

        BreeReactorMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(BreeReactorMainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1496, 21))
        self.menuProjetos = QMenu(self.menubar)
        self.menuProjetos.setObjectName(u"menuProjetos")
        self.menuBancos_de_dados = QMenu(self.menubar)
        self.menuBancos_de_dados.setObjectName(u"menuBancos_de_dados")
        self.menuAcess_rios = QMenu(self.menubar)
        self.menuAcess_rios.setObjectName(u"menuAcess_rios")
        self.menuComplementares = QMenu(self.menubar)
        self.menuComplementares.setObjectName(u"menuComplementares")
        self.menuRelat_rios = QMenu(self.menubar)
        self.menuRelat_rios.setObjectName(u"menuRelat_rios")
        BreeReactorMainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(BreeReactorMainWindow)
        self.statusbar.setObjectName(u"statusbar")
        BreeReactorMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(BreeReactorMainWindow)
        self.toolBar.setObjectName(u"toolBar")
        BreeReactorMainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuProjetos.menuAction())
        self.menubar.addAction(self.menuBancos_de_dados.menuAction())
        self.menubar.addAction(self.menuAcess_rios.menuAction())
        self.menubar.addAction(self.menuComplementares.menuAction())
        self.menubar.addAction(self.menuRelat_rios.menuAction())
        self.menuProjetos.addAction(self.actionNovo_projeto)
        self.menuProjetos.addAction(self.actionCarregar_projeto)
        self.menuProjetos.addAction(self.actionDados_do_sistema)
        self.menuProjetos.addAction(self.actionCorrentes_harm_nicas)
        self.menuProjetos.addAction(self.actionDados_construtivos)
        self.menuProjetos.addAction(self.actionFim)
        self.menuProjetos.addAction(self.actionSalvar_projeto)
        self.menuBancos_de_dados.addAction(self.actionProjetos)
        self.menuBancos_de_dados.addAction(self.actionCondutores)
        self.menuBancos_de_dados.addAction(self.actionMateriais)
        self.menuBancos_de_dados.addAction(self.actionEspessuras_das_fibras)
        self.menuBancos_de_dados.addAction(self.actionCruzetas)
        self.menuAcess_rios.addAction(self.actionSe_o_de_taps)
        self.menuAcess_rios.addAction(self.actionAn_is_de_perdas)
        self.menuAcess_rios.addAction(self.actionIsoladores_Hardware)
        self.menuComplementares.addAction(self.actionMateriais_e_custos)
        self.menuComplementares.addAction(self.actionIndut_ncia_3_x_Fases)
        self.menuComplementares.addAction(self.actionIndut_ncia_m_dulos_iguais_em_s_rie_empilhados)
        self.menuComplementares.addAction(self.actionFor_as_de_curto_e_vento)
        self.menuComplementares.addAction(self.actionS_smico)
        self.menuComplementares.addAction(self.actionCampo_magn_tico)
        self.menuRelat_rios.addAction(self.actionCustos)
        self.toolBar.addAction(self.actionNovo_projeto)
        self.toolBar.addAction(self.actionCarregar_projeto)
        self.toolBar.addAction(self.actionDados_do_sistema)
        self.toolBar.addAction(self.actionCorrentes_harm_nicas)
        self.toolBar.addAction(self.actionDados_construtivos)
        self.toolBar.addAction(self.actionSalvar_projeto)
        self.toolBar.addAction(self.actionFor_as_de_curto_e_vento)
        self.toolBar.addAction(self.actionIndut_ncia_m_dulos_iguais_em_s_rie_empilhados)
        self.toolBar.addAction(self.actionIndut_ncia_3_x_Fases)
        self.toolBar.addAction(self.actionEspessuras_das_fibras)
        self.toolBar.addAction(self.actionCruzetas)
        self.toolBar.addAction(self.actionIsoladores_Hardware)
        self.toolBar.addAction(self.actionS_smico)
        self.toolBar.addAction(self.actionSe_o_de_taps)
        self.toolBar.addAction(self.actionAn_is_de_perdas)
        self.toolBar.addAction(self.actionMateriais_e_custos)

        self.retranslateUi(BreeReactorMainWindow)
        self.actionFim.destroyed.connect(BreeReactorMainWindow.close)

        QMetaObject.connectSlotsByName(BreeReactorMainWindow)
    # setupUi

    def retranslateUi(self, BreeReactorMainWindow):
        BreeReactorMainWindow.setWindowTitle(QCoreApplication.translate("BreeReactorMainWindow", u"bree Reactor Design", None))
        self.actionNovo_projeto.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Novo projeto", None))
        self.actionCondutores.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Condutores", None))
        self.actionMateriais.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Materiais...", None))
        self.actionProjetos.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Projetos", None))
        self.actionFim.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Fim", None))
        self.actionDados_do_sistema.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Dados do sistema...", None))
        self.actionDados_construtivos.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Dados construtivos", None))
        self.actionCarregar_projeto.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Carregar projeto", None))
        self.actionSalvar_projeto.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Salvar projeto", None))
        self.actionCorrentes_harm_nicas.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Correntes harm\u00f4nicas", None))
        self.actionSe_o_de_taps.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Se\u00e7\u00e3o de taps", None))
        self.actionAn_is_de_perdas.setText(QCoreApplication.translate("BreeReactorMainWindow", u"An\u00e9is de perdas", None))
        self.actionIsoladores_Hardware.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Isoladores & Hardware", None))
        self.actionFor_as_de_curto_e_vento.setText(QCoreApplication.translate("BreeReactorMainWindow", u"For\u00e7as de curto 2 ou 3 x fases e vento", None))
        self.actionS_smico.setText(QCoreApplication.translate("BreeReactorMainWindow", u"S\u00edsmico", None))
        self.actionCampo_magn_tico.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Campo magn\u00e9tico", None))
        self.actionIndut_ncia_3_x_Fases.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Indut\u00e2ncia Trf\u00e1sico m\u00f3dulos empilhados", None))
        self.actionMateriais_e_custos.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Materiais e custos", None))
        self.actionCustos.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Custos", None))
        self.actionEspessuras_das_fibras.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Espessuras das fibras", None))
        self.actionCruzetas.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Cruzetas", None))
        self.actionIndut_ncia_m_dulos_iguais_em_s_rie_empilhados.setText(QCoreApplication.translate("BreeReactorMainWindow", u"Indut\u00e2ncia m\u00f3dulos iguais em s\u00e9rie empilhados", None))
        self.labelImage.setText("")
        self.menuProjetos.setTitle(QCoreApplication.translate("BreeReactorMainWindow", u"Projetos", None))
        self.menuBancos_de_dados.setTitle(QCoreApplication.translate("BreeReactorMainWindow", u"Bancos de dados", None))
        self.menuAcess_rios.setTitle(QCoreApplication.translate("BreeReactorMainWindow", u"Acess\u00f3rios", None))
        self.menuComplementares.setTitle(QCoreApplication.translate("BreeReactorMainWindow", u"Complementares", None))
        self.menuRelat_rios.setTitle(QCoreApplication.translate("BreeReactorMainWindow", u"Relat\u00f3rios", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("BreeReactorMainWindow", u"toolBar", None))
    # retranslateUi

