# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_system_bree.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(405, 299)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bt_CpEn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.bt_CpEn.setFont(font)
        self.bt_CpEn.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"alternate-background-color: rgb(170, 170, 255);")
        self.bt_CpEn.setFlat(False)
        self.bt_CpEn.setObjectName("bt_CpEn")
        self.verticalLayout.addWidget(self.bt_CpEn)
        self.bt_CpBr = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.bt_CpBr.setFont(font)
        self.bt_CpBr.setStyleSheet("background-color: rgb(170, 170, 0);")
        self.bt_CpBr.setObjectName("bt_CpBr")
        self.verticalLayout.addWidget(self.bt_CpBr)
        self.bt_CHF = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.bt_CHF.setFont(font)
        self.bt_CHF.setStyleSheet("background-color: rgb(170, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.bt_CHF.setObjectName("bt_CHF")
        self.verticalLayout.addWidget(self.bt_CHF)
        self.bt_FI = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.bt_FI.setFont(font)
        self.bt_FI.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_FI.setObjectName("bt_FI")
        self.verticalLayout.addWidget(self.bt_FI)
        self.bt_RS = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.bt_RS.setFont(font)
        self.bt_RS.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.bt_RS.setObjectName("bt_RS")
        self.verticalLayout.addWidget(self.bt_RS)
        self.bt_RSP = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.bt_RSP.setFont(font)
        self.bt_RSP.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.bt_RSP.setObjectName("bt_RSP")
        self.verticalLayout.addWidget(self.bt_RSP)
        self.bt_reactor = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.bt_reactor.setFont(font)
        self.bt_reactor.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.bt_reactor.setObjectName("bt_reactor")
        self.verticalLayout.addWidget(self.bt_reactor)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistemas de cáculos bree"))
        self.bt_CpEn.setText(_translate("MainWindow", "Capacitor de Potência Eixos Americanos"))
        self.bt_CpBr.setText(_translate("MainWindow", "Capacitor de Potência Eixos Brasileiros"))
        self.bt_CHF.setText(_translate("MainWindow", "Capacitor de Alta Frequência"))
        self.bt_FI.setText(_translate("MainWindow", "Fusível Interno"))
        self.bt_RS.setText(_translate("MainWindow", "Resistor de descarga Série"))
        self.bt_RSP.setText(_translate("MainWindow", "Resistor Série/Paralelo"))
        self.bt_reactor.setText(_translate("MainWindow", "Reator de Núcleo de Ar"))
