# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\wmeba\OneDrive\Documentos\Python Scripts\Bree\Gui\SysDataDlg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_DialogSys(object):
    def setupUi(self, DialogSys):
        DialogSys.setObjectName("DialogSys")
        DialogSys.resize(564, 484)
        DialogSys.setSizeGripEnabled(False)
        DialogSys.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogSys)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        self.frequNciaHzLabel = QtWidgets.QLabel(DialogSys)
        self.frequNciaHzLabel.setObjectName("frequNciaHzLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frequNciaHzLabel)
        self.inputFreq = QtWidgets.QLineEdit(DialogSys)
        self.inputFreq.setObjectName("inputFreq")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputFreq)
        self.tensONominalVLabel = QtWidgets.QLabel(DialogSys)
        self.tensONominalVLabel.setObjectName("tensONominalVLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tensONominalVLabel)
        self.inputVn = QtWidgets.QLineEdit(DialogSys)
        self.inputVn.setObjectName("inputVn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputVn)
        self.nBIKVLabel = QtWidgets.QLabel(DialogSys)
        self.nBIKVLabel.setObjectName("nBIKVLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nBIKVLabel)
        self.inputNBI = QtWidgets.QLineEdit(DialogSys)
        self.inputNBI.setObjectName("inputNBI")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inputNBI)
        self.normaLabel = QtWidgets.QLabel(DialogSys)
        self.normaLabel.setObjectName("normaLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.normaLabel)
        self.normaComboBox = QtWidgets.QComboBox(DialogSys)
        self.normaComboBox.setObjectName("normaComboBox")
        self.normaComboBox.addItem("")
        self.normaComboBox.addItem("")
        self.normaComboBox.addItem("")
        self.normaComboBox.addItem("")
        self.normaComboBox.addItem("")
        self.normaComboBox.addItem("")
        self.normaComboBox.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.normaComboBox)
        self.altitudeMLabel = QtWidgets.QLabel(DialogSys)
        self.altitudeMLabel.setObjectName("altitudeMLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.altitudeMLabel)
        self.imputAltitude = QtWidgets.QLineEdit(DialogSys)
        self.imputAltitude.setObjectName("imputAltitude")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.imputAltitude)
        self.imputVento = QtWidgets.QLabel(DialogSys)
        self.imputVento.setObjectName("imputVento")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.imputVento)
        self.velocidadeDoVentoKmHLineEdit = QtWidgets.QLineEdit(DialogSys)
        self.velocidadeDoVentoKmHLineEdit.setObjectName("velocidadeDoVentoKmHLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.velocidadeDoVentoKmHLineEdit)
        self.labelICC = QtWidgets.QLabel(DialogSys)
        self.labelICC.setObjectName("labelICC")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelICC)
        self.imputICC = QtWidgets.QLineEdit(DialogSys)
        self.imputICC.setObjectName("imputICC")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.imputICC)
        self.duraOSLabel = QtWidgets.QLabel(DialogSys)
        self.duraOSLabel.setObjectName("duraOSLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.duraOSLabel)
        self.imputTempo = QtWidgets.QLineEdit(DialogSys)
        self.imputTempo.setObjectName("imputTempo")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.imputTempo)
        self.iccPicoKALabel = QtWidgets.QLabel(DialogSys)
        self.iccPicoKALabel.setObjectName("iccPicoKALabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.iccPicoKALabel)
        self.imputPico = QtWidgets.QLineEdit(DialogSys)
        self.imputPico.setObjectName("imputPico")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.imputPico)
        self.temperaturaAmbienteCLabel = QtWidgets.QLabel(DialogSys)
        self.temperaturaAmbienteCLabel.setObjectName("temperaturaAmbienteCLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.temperaturaAmbienteCLabel)
        self.imputTamb = QtWidgets.QLineEdit(DialogSys)
        self.imputTamb.setObjectName("imputTamb")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.imputTamb)
        self.temperaturaDeReferNciaCLabel = QtWidgets.QLabel(DialogSys)
        self.temperaturaDeReferNciaCLabel.setObjectName("temperaturaDeReferNciaCLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.temperaturaDeReferNciaCLabel)
        self.imputTref = QtWidgets.QLineEdit(DialogSys)
        self.imputTref.setObjectName("imputTref")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.imputTref)
        self.indutNciaNominalMHLabel = QtWidgets.QLabel(DialogSys)
        self.indutNciaNominalMHLabel.setObjectName("indutNciaNominalMHLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.indutNciaNominalMHLabel)
        self.imputLn = QtWidgets.QLineEdit(DialogSys)
        self.imputLn.setObjectName("imputLn")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.imputLn)
        self.indutNciaAlvoMHLabel = QtWidgets.QLabel(DialogSys)
        self.indutNciaAlvoMHLabel.setObjectName("indutNciaAlvoMHLabel")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.indutNciaAlvoMHLabel)
        self.imputLtarget = QtWidgets.QLineEdit(DialogSys)
        self.imputLtarget.setObjectName("imputLtarget")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.imputLtarget)
        self.correnteNominalALabel = QtWidgets.QLabel(DialogSys)
        self.correnteNominalALabel.setObjectName("correnteNominalALabel")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.correnteNominalALabel)
        self.imputInominal = QtWidgets.QLineEdit(DialogSys)
        self.imputInominal.setObjectName("imputInominal")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.imputInominal)
        self.correnteTotalALabel = QtWidgets.QLabel(DialogSys)
        self.correnteTotalALabel.setObjectName("correnteTotalALabel")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.correnteTotalALabel)
        self.imputITotal = QtWidgets.QLineEdit(DialogSys)
        self.imputITotal.setObjectName("imputITotal")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.imputITotal)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_Ok = QtWidgets.QPushButton(DialogSys)
        self.btn_Ok.setObjectName("btn_Ok")
        self.horizontalLayout.addWidget(self.btn_Ok)
        self.btn_cancel = QtWidgets.QPushButton(DialogSys)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogSys)
        QtCore.QMetaObject.connectSlotsByName(DialogSys)

    def retranslateUi(self, DialogSys):
        _translate = QtCore.QCoreApplication.translate
        DialogSys.setWindowTitle(_translate("DialogSys", "Dados do sistema"))
        self.frequNciaHzLabel.setText(_translate("DialogSys", "Frequência (Hz)"))
        self.inputFreq.setText(_translate("DialogSys", "60"))
        self.inputFreq.setPlaceholderText(_translate("DialogSys", "Entre com a frequência industrial"))
        self.tensONominalVLabel.setText(_translate("DialogSys", "Tensão nominal (V)"))
        self.nBIKVLabel.setText(_translate("DialogSys", "NBI (kV)"))
        self.normaLabel.setText(_translate("DialogSys", "Norma"))
        self.normaComboBox.setItemText(0, _translate("DialogSys", "NBR 5119 - Reator"))
        self.normaComboBox.setItemText(1, _translate("DialogSys", "NBR 8119 - Bobina"))
        self.normaComboBox.setItemText(2, _translate("DialogSys", "IEC 60076-6 - Reator"))
        self.normaComboBox.setItemText(3, _translate("DialogSys", "IEC 60353 - Bobina"))
        self.normaComboBox.setItemText(4, _translate("DialogSys", "ANSI C57.21 - Reator Shunt"))
        self.normaComboBox.setItemText(5, _translate("DialogSys", "ANSI C93.3 - Bobina"))
        self.normaComboBox.setItemText(6, _translate("DialogSys", "ANSI C57.21 - Reator Serie"))
        self.altitudeMLabel.setText(_translate("DialogSys", "Altitude (m)"))
        self.imputAltitude.setText(_translate("DialogSys", "1000"))
        self.imputVento.setText(_translate("DialogSys", "Velocidade do vento (km/h)"))
        self.velocidadeDoVentoKmHLineEdit.setText(_translate("DialogSys", "120"))
        self.labelICC.setText(_translate("DialogSys", "Corrente de curto-circuito (kA)"))
        self.duraOSLabel.setText(_translate("DialogSys", "Duração (s)"))
        self.imputTempo.setText(_translate("DialogSys", "1"))
        self.iccPicoKALabel.setText(_translate("DialogSys", "Icc Pico (kA)"))
        self.temperaturaAmbienteCLabel.setText(_translate("DialogSys", "Temperatura ambiente (°C)"))
        self.imputTamb.setText(_translate("DialogSys", "40"))
        self.temperaturaDeReferNciaCLabel.setText(_translate("DialogSys", "Temperatura de referência (°C)"))
        self.indutNciaNominalMHLabel.setText(_translate("DialogSys", "Indutância nominal (mH)"))
        self.indutNciaAlvoMHLabel.setText(_translate("DialogSys", "Indutância alvo (mH)"))
        self.correnteNominalALabel.setText(_translate("DialogSys", "Corrente nominal (A)"))
        self.correnteTotalALabel.setText(_translate("DialogSys", "Corrente total (A)"))
        self.btn_Ok.setText(_translate("DialogSys", "Ok"))
        self.btn_cancel.setText(_translate("DialogSys", "Cancelar"))

