# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_reactor_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BreeReactorMainWindow(object):
    def setupUi(self, BreeReactorMainWindow):
        BreeReactorMainWindow.setObjectName("BreeReactorMainWindow")
        BreeReactorMainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(BreeReactorMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        BreeReactorMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BreeReactorMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuProjetos = QtWidgets.QMenu(self.menubar)
        self.menuProjetos.setObjectName("menuProjetos")
        self.menuBancos_de_dados = QtWidgets.QMenu(self.menubar)
        self.menuBancos_de_dados.setObjectName("menuBancos_de_dados")
        BreeReactorMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BreeReactorMainWindow)
        self.statusbar.setObjectName("statusbar")
        BreeReactorMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(BreeReactorMainWindow)
        self.toolBar.setObjectName("toolBar")
        BreeReactorMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNovo_projeto = QtWidgets.QAction(BreeReactorMainWindow)
        self.actionNovo_projeto.setObjectName("actionNovo_projeto")
        self.actionCondutores = QtWidgets.QAction(BreeReactorMainWindow)
        self.actionCondutores.setObjectName("actionCondutores")
        self.actionMateriais = QtWidgets.QAction(BreeReactorMainWindow)
        self.actionMateriais.setObjectName("actionMateriais")
        self.actionProjetos = QtWidgets.QAction(BreeReactorMainWindow)
        self.actionProjetos.setObjectName("actionProjetos")
        self.actionFim = QtWidgets.QAction(BreeReactorMainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bree/sair-alt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFim.setIcon(icon)
        self.actionFim.setObjectName("actionFim")
        self.actionDados_do_sistema = QtWidgets.QAction(BreeReactorMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/bree/configuracoes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDados_do_sistema.setIcon(icon1)
        self.actionDados_do_sistema.setObjectName("actionDados_do_sistema")
        self.actionDados_construtivos = QtWidgets.QAction(BreeReactorMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/bree/ruler.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDados_construtivos.setIcon(icon2)
        self.actionDados_construtivos.setObjectName("actionDados_construtivos")
        self.actionCarregar_projeto = QtWidgets.QAction(BreeReactorMainWindow)
        self.actionCarregar_projeto.setObjectName("actionCarregar_projeto")
        self.actionSalvar_projeto = QtWidgets.QAction(BreeReactorMainWindow)
        self.actionSalvar_projeto.setObjectName("actionSalvar_projeto")
        self.menuProjetos.addAction(self.actionNovo_projeto)
        self.menuProjetos.addAction(self.actionCarregar_projeto)
        self.menuProjetos.addAction(self.actionDados_do_sistema)
        self.menuProjetos.addAction(self.actionDados_construtivos)
        self.menuProjetos.addAction(self.actionFim)
        self.menuProjetos.addAction(self.actionSalvar_projeto)
        self.menuBancos_de_dados.addAction(self.actionProjetos)
        self.menuBancos_de_dados.addAction(self.actionCondutores)
        self.menuBancos_de_dados.addAction(self.actionMateriais)
        self.menubar.addAction(self.menuProjetos.menuAction())
        self.menubar.addAction(self.menuBancos_de_dados.menuAction())
        self.toolBar.addAction(self.actionDados_do_sistema)
        self.toolBar.addAction(self.actionDados_construtivos)

        self.retranslateUi(BreeReactorMainWindow)
        self.actionFim.destroyed.connect(BreeReactorMainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BreeReactorMainWindow)

    def retranslateUi(self, BreeReactorMainWindow):
        _translate = QtCore.QCoreApplication.translate
        BreeReactorMainWindow.setWindowTitle(_translate("BreeReactorMainWindow", "bree Reactor Design"))
        self.menuProjetos.setTitle(_translate("BreeReactorMainWindow", "Projetos"))
        self.menuBancos_de_dados.setTitle(_translate("BreeReactorMainWindow", "Bancos de dados"))
        self.toolBar.setWindowTitle(_translate("BreeReactorMainWindow", "toolBar"))
        self.actionNovo_projeto.setText(_translate("BreeReactorMainWindow", "Novo projeto"))
        self.actionCondutores.setText(_translate("BreeReactorMainWindow", "Condutores"))
        self.actionMateriais.setText(_translate("BreeReactorMainWindow", "Materiais..."))
        self.actionProjetos.setText(_translate("BreeReactorMainWindow", "Projetos"))
        self.actionFim.setText(_translate("BreeReactorMainWindow", "Fim"))
        self.actionDados_do_sistema.setText(_translate("BreeReactorMainWindow", "Dados do sistema..."))
        self.actionDados_construtivos.setText(_translate("BreeReactorMainWindow", "Dados construtivos"))
        self.actionCarregar_projeto.setText(_translate("BreeReactorMainWindow", "Carregar projeto"))
        self.actionSalvar_projeto.setText(_translate("BreeReactorMainWindow", "Salvar projeto"))
import bree_rc
